# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Terraform"
on:
  push:
    branches:
      - dev
  pull_request:
      branches:
        - dev

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/504579259344/locations/global/workloadIdentityPools/github/providers/github-actions
  SERVICE_ACCOUNT: tsting@rbadawi-host-vpc.iam.gserviceaccount.com
  ENVIRONMENT: dev

jobs:
  terraform-dev-deployment:
    name: "Terraform on Development Environment"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          WORKLOAD_IDENTITY_PROVIDER: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          SERVICE_ACCOUNT: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: '3600s' # optional, default: '3600s' (1 hour)
      # Terraform steps

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.1
          cli_config_credentials_token: ${{ steps.auth.outputs.access_token }}

      - name: Terraform Format
        id: fmt-on-development
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init-on-development
        run: |-
          TF_LOG=TRACE terraform init \
          -backend-config='./environment/dev/backend.tf'

      - name: Terraform Validate
        id: validate-on-development
        run: terraform validate -no-color


      - name: Terraform Plan
        id: plan-on-development
        if: github.event_name == 'pull_request'
        run: terraform plan -var-file='environment/dev/terraform.tfvars' -no-color
          
        continue-on-error: true

      - name: Attach plan to PR
        id: attach-plan-on-development
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan-on-development.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt-on-development.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init-on-development.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate-on-development.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan-on-development.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan-on-development.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: terraform-apply-on-development
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: terraform apply -var-file='environment/dev/terraform.tfvars' -auto-approve

      # End Terraform Development Steps